name: fl_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^2.1.0
  #open_street_map_search_and_pick:
  #geocode:  # Use the latest version
  #geocoding: ^2.1.0
  geolocator: ^10.0.0
  location: ^5.0.0
  webview_flutter: ^4.2.4
  #webview_flutter: ^2.0.14
  #flutter_inappwebview: ^5.0.5
  http: ^0.13.3
  dio: ^5.2.0
  dio_cookie_manager: ^3.1.0
  hypertrack_plugin: ^1.1.3
  web_socket_channel: ^2.4.0
  firebase_messaging: ^14.6.7
  firebase_core: ^2.15.1
  shared_preferences: ^2.2.1
  flutter_dialogs: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_ringtone_player: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
