// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "constants.dart";
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: web_fb_api_key,
    appId: web_fb_app_id,
    messagingSenderId: '193888611770',
    projectId: 'wevuuge-ak256',
    authDomain: 'wevuuge-ak256.firebaseapp.com',
    storageBucket: 'wevuuge-ak256.appspot.com',
    measurementId: 'G-SNQN9YZS0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: and4_fb_api_key,
    appId: and4_fb_app_id,
    messagingSenderId: '193888611770',
    projectId: 'wevuuge-ak256',
    storageBucket: 'wevuuge-ak256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ios_fb_api_key,
    appId: ios_fb_app_id,
    messagingSenderId: '193888611770',
    projectId: 'wevuuge-ak256',
    storageBucket: 'wevuuge-ak256.appspot.com',
    iosBundleId: 'com.example.flTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: macos_fb_api_key,
    appId: macos_fb_app_id,
    messagingSenderId: '193888611770',
    projectId: 'wevuuge-ak256',
    storageBucket: 'wevuuge-ak256.appspot.com',
    iosBundleId: 'com.example.flTest.RunnerTests',
  );
}
